kotlin.code.style=official
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.mpp.androidSourceSetLayoutV2AndroidStyleDirs.nowarn=true
android.useAndroidX=true

# Project coordinates
group=dev.t0rzz.samloaderreloaded
version=1.0.38

kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.enableCInteropCommonization.nowarn=true

# Increase Gradle daemon memory to avoid OOMs during build and problem report generation
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
