name: Build GUI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'samloader/gui.py'
      - 'samloader/__init__.py'
      - 'samloader/versionfetch.py'
      - 'samloader/fusclient.py'
      - 'samloader/crypt.py'
      - 'samloader/imei.py'
      - 'samloader/main.py'
      - 'samloader/request.py'
      - 'samloader/regions.py'
      - 'samloader/data/**'
      - 'setup.py'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows-gui:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            setup.py

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install . pyinstaller

      - name: Get version
        id: getver
        run: |
          $ver = python -c "import samloader; print(samloader.__version__)"
          echo "ver=$ver" >> $env:GITHUB_OUTPUT

      - name: Build GUI exe
        run: |
          pyinstaller --noconfirm --onefile --windowed -n samloader-gui --collect-data certifi --add-data "samloader\data\regions.json;samloader\data" samloader\gui.py

      - name: Upload artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: samloader-gui-${{ steps.getver.outputs.ver }}-win
          path: dist/samloader-gui.exe

      - name: Upload to Release
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.T0RZZ_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: "SamLoader GUI ${{ steps.getver.outputs.ver }}"
          files: |
            dist/samloader-gui.exe